sudo: false
language: groovy
jdk: oraclejdk8
env: TERM=dumb
cache:
  directories:
  - $HOME/.gradle

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_install:
  - chmod +x gradlew
  - git fetch
  - git config user.email "rzabini@@users.noreply.github.com"
  - git config user.name "Travis-CI"
  - git config url.https://.insteadOf git://
  - git checkout -qf $TRAVIS_BRANCH
# skip default gradlew assemble
install:
  - echo "skip default gradlew assemble"
script:
- './gradlew build --info --stacktrace'


after_success:
  - ./gradlew jacocoTestReport coveralls
